### ISSUE TITLE
Readme / documentation improvements.

### ISSUE THREAD

**Issue by kindly** [OpenDataServices/standard-search#11]
Readme needs a better descriptions of how this tool works and how to use it.  Potentially a documentation site is needed if this get large.

Main area of focus

- OCDS command line tool
- API usage
- Dev documentation as to how add extra sources.

**Comment by kindly** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Document and improve standard-search](https://trello.com/c/31F2W1nd/7-document-and-improve-standard-search)

**Comment by robredpath** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Better documentation for standard-search](https://trello.com/c/8jqroXAC/37-better-documentation-for-standard-search)

**Comment by ghost** [comment]
Done
