### ISSUE TITLE
FYI, OCP is switching to ocds-index library

### ISSUE THREAD

**Issue by jpmckinney** [OpenDataServices/standard-search#29]
For the standard documentation, this repository would send, in sequence, 260 HTTP requests (65 per language). This would take minutes, and sometimes cause documentation builds to fail as it was taking too long, especially if multiple builds were occurring simultaneously.

A different approach was taken, where files were instead crawled locally (before deployment), and then those results were pushed to Elasticsearch at once. This took seconds, instead of minutes.

If you want to continue developing the remote retrieval strategy, you might as well start from this point in OCP's fork's history, where tests were added: https://github.com/open-contracting-archive/standard-search/tree/955c1f7a4e81e0b99a67ce66350bff673221bdf7

If you want to continue developing a Django app proxy, but have a management command to crawl local files, you can continue from https://github.com/open-contracting-archive/standard-search

OCP has instead developed a Python package to crawl local files and submit them to Elasticsearch: https://pypi.org/project/ocdsindex/ Here are its differences:

- Crawl:
  - Crawl locally.
  - Don't include title in text.
  - Normalize whitespace in text.
  - Easy to extend: just add a Click command and an extract method.
- Index:
  - Index using bulk API.
  - Omit language from base_url (indices are already segmented by language).
  - Add created_at field, to be able to expire old branches.
- QA:
  - Fully tested.
  - Fully documented.
- Other:
  - Add expire command.
  - Update for ES 7.

The 1.1-dev branch of the OCDS documentation was indexed using both the new and old code. Elasticsearch contents were dumped with https://github.com/elasticsearch-dump/elasticsearch-dump and compared using the script below. There were no relevant differences in what gets indexed.

Happy to receive PRs for ocds-index if it's useful for other standards.

The next step for OCP is to update the Elasticsearch deployment, so that indexes can be created/updated using basic authentication over SSL (communicating directly with Elasticsearch), and so that indexes can be queried. As such, we hope to eliminate the need for a Django app.

```python
import json
import re
from urllib.parse import urlparse


def read(filename):
    data = {}
    with open(filename) as f:
        for line in f:
            document = json.loads(line)
            data[document["_id"]] = document["_source"]

    return data


def symmetric_difference(a, b):
    difference = set(a) ^ set(b)
    if difference:
        print(difference)


fields = {"url", "title", "text", "base_url"}

# The old code would replace double-spaces with a newline:
# https://github.com/open-contracting-archive/standard-search/commit/6f51a96c27677a4e96b633b421b69615813b3e7f#commitcomment-44587471
#
# I've compared what gets indexed using the old code and the new code (which omits this step), and the results are
# identical (except where the old code incorrectly inserted a newline in the middle of a sentence, etc.). It might be
# that lxml (used in the new code) inserts newlines where BeautifulSoup didn't (from the old code).
errors = {
    # Double-space mid-sentence.
    "towards\ncompletion",
    "announced\nwith",
    "separates\nobjects",
    "The\nUNCITRAL",
    "descriptions,\nwe",
    "the\nitemClassificationScheme",
    "can\nunderstand",
    "award\nthe",
    "buyers,\nsuppliers",
    "local\nclassification.scheme",
    "publication,\nwould",
    "a\nsub-contracting",
    "Armanda\nArmanda",
    "0492\n- 252163",
    # Double-space after full-stop in same paragraph.
    "information.\nSuch",
    "House.\nThe",
    "task.\nAn",
    "standard.\nWe",
    "procurement.\nA",
    # Double-space in same paragraph.
    "because\n(a)",
    "or\n(b)",
}

expected = read("a.json")
actual = read("b.json")

# Same document IDs.
symmetric_difference(expected, actual)

count = 0
for url in expected:
    a = expected[url]
    b = actual[url]

    b.pop("created_at")

    # Use HTTPS.
    a["url"] = urlparse(a["url"])._replace(scheme="https").geturl()
    a["base_url"] = urlparse(a["base_url"])._replace(scheme="https").geturl()
    # Omit language directory.
    a["base_url"] = a["base_url"][:-3]
    # Compact newlines.
    a["text"] = re.sub(r"\n\n+", "\n", a["text"]).strip()
    # Remove unusual whitespace.
    a["text"] = a["text"].replace("Center.\xa0 ", "Center. ")
    # Remove heading from text.
    if "\n" in a["text"]:
        a["text"] = a["text"].split("\n", 1)[1]
    else:
        a["text"] = ""
    # Fix incorrect double-space conversion to newline.
    for error in errors:
        a["text"] = a["text"].replace(error, error.replace("\n", " "))

    # Same document fields.
    symmetric_difference(a, b)

    assert set(a) == fields

    for field in fields:
        if a[field] != b[field]:
            count += 1
            print(f"{field}:\n{a[field]!r} !=\n{b[field]!r}\n")

print(count)
```

**Comment by robredpath** [comment]
Thanks @jpmckinney - that's useful context and an interesting change. Thanks for letting us know!
